// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VH.Data;

#nullable disable

namespace VH.Data.Migrations
{
    [DbContext(typeof(VHERPContext))]
    [Migration("20260214220646_PuestosYAnalitics")]
    partial class PuestosYAnalitics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VH.Services.Entities.AlertaConsumo", b =>
                {
                    b.Property<int>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlerta"));

                    b.Property<decimal?>("CostoEstimado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Desviacion")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EstadoAlerta")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRevision")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int?>("IdEntrega")
                        .HasColumnType("int");

                    b.Property<int?>("IdMaterial")
                        .HasColumnType("int");

                    b.Property<int?>("IdProyecto")
                        .HasColumnType("int");

                    b.Property<int?>("IdRequisicion")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuarioReviso")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Severidad")
                        .HasColumnType("int");

                    b.Property<int>("TipoAlerta")
                        .HasColumnType("int");

                    b.Property<string>("ValorEsperado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ValorReal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdAlerta");

                    b.HasIndex("EstadoAlerta");

                    b.HasIndex("FechaGeneracion");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdEntrega");

                    b.HasIndex("IdMaterial");

                    b.HasIndex("IdProyecto");

                    b.HasIndex("IdRequisicion");

                    b.HasIndex("IdUsuarioReviso");

                    b.HasIndex("Severidad");

                    b.ToTable("AlertasConsumo");
                });

            modelBuilder.Entity("VH.Services.Entities.Almacen", b =>
                {
                    b.Property<int>("IdAlmacen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlmacen"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TipoUbicacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdAlmacen");

                    b.HasIndex("IdProyecto");

                    b.ToTable("Almacenes");
                });

            modelBuilder.Entity("VH.Services.Entities.CompraEPP", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompra"));

                    b.Property<decimal>("CantidadComprada")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CantidadDisponible")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAlmacen")
                        .HasColumnType("int");

                    b.Property<int>("IdMaterial")
                        .HasColumnType("int");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdCompra");

                    b.HasIndex("FechaCompra");

                    b.HasIndex("IdAlmacen");

                    b.HasIndex("IdMaterial");

                    b.HasIndex("IdProveedor");

                    b.ToTable("ComprasEPP");
                });

            modelBuilder.Entity("VH.Services.Entities.ConceptoPartida", b =>
                {
                    b.Property<int>("IdPartida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPartida"));

                    b.Property<decimal>("CantidadEstimada")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("int");

                    b.Property<int>("IdUnidadMedida")
                        .HasColumnType("int");

                    b.HasKey("IdPartida");

                    b.HasIndex("IdProyecto");

                    b.HasIndex("IdUnidadMedida");

                    b.ToTable("ConceptosPartidas");
                });

            modelBuilder.Entity("VH.Services.Entities.ConfiguracionMaterialEPP", b =>
                {
                    b.Property<int>("IdConfiguracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConfiguracion"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<decimal?>("CantidadMaximaMensual")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CantidadMaximaPorEntrega")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("FrecuenciaMinimaDias")
                        .HasColumnType("int");

                    b.Property<int>("IdMaterial")
                        .HasColumnType("int");

                    b.Property<bool>("RequiereDevolucion")
                        .HasColumnType("bit");

                    b.Property<int>("UmbralAlertaPorcentaje")
                        .HasColumnType("int");

                    b.Property<int>("VidaUtilDias")
                        .HasColumnType("int");

                    b.HasKey("IdConfiguracion");

                    b.HasIndex("IdMaterial")
                        .IsUnique();

                    b.ToTable("ConfiguracionesMaterialEPP");
                });

            modelBuilder.Entity("VH.Services.Entities.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimoCalculoRiesgo")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("int");

                    b.Property<int?>("IdPuesto")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroNomina")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PuntuacionRiesgoActual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdEmpleado");

                    b.HasIndex("IdProyecto");

                    b.HasIndex("IdPuesto");

                    b.HasIndex("NumeroNomina")
                        .IsUnique();

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("VH.Services.Entities.EntregaEPP", b =>
                {
                    b.Property<int>("IdEntrega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEntrega"));

                    b.Property<decimal>("CantidadEntregada")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCompra")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TallaEntregada")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdEntrega");

                    b.HasIndex("FechaEntrega");

                    b.HasIndex("IdCompra");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("EntregasEPP");
                });

            modelBuilder.Entity("VH.Services.Entities.EstadisticaEmpleadoMensual", b =>
                {
                    b.Property<int>("IdEstadistica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadistica"));

                    b.Property<int>("AlertasGeneradas")
                        .HasColumnType("int");

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<decimal>("CostoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("int");

                    b.Property<int>("MaterialesDistintos")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<decimal>("PromedioDesviacionVidaUtil")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PuntuacionRiesgo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalEntregas")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalUnidades")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("IdEstadistica");

                    b.HasIndex("PuntuacionRiesgo");

                    b.HasIndex("IdEmpleado", "Anio", "Mes")
                        .IsUnique();

                    b.HasIndex("IdProyecto", "Anio", "Mes");

                    b.ToTable("EstadisticasEmpleadoMensual");
                });

            modelBuilder.Entity("VH.Services.Entities.EstadisticaProyectoMensual", b =>
                {
                    b.Property<int>("IdEstadistica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadistica"));

                    b.Property<int>("AlertasCriticas")
                        .HasColumnType("int");

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<decimal>("CostoPromedioPorEmpleado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DesviacionPresupuesto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<decimal>("PresupuestoAsignado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalAlertas")
                        .HasColumnType("int");

                    b.Property<int>("TotalEmpleados")
                        .HasColumnType("int");

                    b.Property<int>("TotalEntregas")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalUnidades")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("IdEstadistica");

                    b.HasIndex("IdProyecto", "Anio", "Mes")
                        .IsUnique();

                    b.ToTable("EstadisticasProyectoMensual");
                });

            modelBuilder.Entity("VH.Services.Entities.Inventario", b =>
                {
                    b.Property<int>("IdInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInventario"));

                    b.Property<decimal>("Existencia")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("FechaUltimoMovimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAlmacen")
                        .HasColumnType("int");

                    b.Property<int>("IdMaterial")
                        .HasColumnType("int");

                    b.Property<decimal>("StockMaximo")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("StockMinimo")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("UbicacionPasillo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdInventario");

                    b.HasIndex("IdMaterial");

                    b.HasIndex("IdAlmacen", "IdMaterial")
                        .IsUnique();

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("VH.Services.Entities.LogActividad", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLog"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DireccionIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Entidad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdEntidad")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdLog");

                    b.HasIndex("Fecha");

                    b.HasIndex("IdUsuario");

                    b.ToTable("LogsActividad");
                });

            modelBuilder.Entity("VH.Services.Entities.MaterialEPP", b =>
                {
                    b.Property<int>("IdMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMaterial"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaRiesgo")
                        .HasColumnType("int");

                    b.Property<decimal>("CostoUnitarioEstimado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EsDesechable")
                        .HasColumnType("bit");

                    b.Property<int>("IdUnidadMedida")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("VidaUtilDiasDefault")
                        .HasColumnType("int");

                    b.HasKey("IdMaterial");

                    b.HasIndex("IdUnidadMedida");

                    b.ToTable("MaterialesEPP");
                });

            modelBuilder.Entity("VH.Services.Entities.Modulo", b =>
                {
                    b.Property<int>("IdModulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModulo"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ControllerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdModuloPadre")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("IdModulo");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("IdModuloPadre");

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("VH.Services.Entities.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RFC")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdProveedor");

                    b.HasIndex("RFC")
                        .IsUnique();

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("VH.Services.Entities.Proyecto", b =>
                {
                    b.Property<int>("IdProyecto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProyecto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("EmpleadosEsperados")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFinEstimada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("PresupuestoEPPMensual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PresupuestoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoObra")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdProyecto");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("VH.Services.Entities.Puesto", b =>
                {
                    b.Property<int>("IdPuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPuesto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NivelRiesgoEPP")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdPuesto");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Puestos");
                });

            modelBuilder.Entity("VH.Services.Entities.RequisicionEPP", b =>
                {
                    b.Property<int>("IdRequisicion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRequisicion"));

                    b.Property<int>("EstadoRequisicion")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmaDigital")
                        .HasMaxLength(500000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoEvidencia")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("IdAlmacen")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpleadoRecibe")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuarioAprueba")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdUsuarioEntrega")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdUsuarioSolicita")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Justificacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NumeroRequisicion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdRequisicion");

                    b.HasIndex("EstadoRequisicion");

                    b.HasIndex("FechaSolicitud");

                    b.HasIndex("IdAlmacen");

                    b.HasIndex("IdEmpleadoRecibe");

                    b.HasIndex("IdUsuarioAprueba");

                    b.HasIndex("IdUsuarioEntrega");

                    b.HasIndex("IdUsuarioSolicita");

                    b.HasIndex("NumeroRequisicion")
                        .IsUnique();

                    b.ToTable("RequisicionesEPP");
                });

            modelBuilder.Entity("VH.Services.Entities.RequisicionEPPDetalle", b =>
                {
                    b.Property<int>("IdRequisicionDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRequisicionDetalle"));

                    b.Property<decimal?>("CantidadEntregada")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CantidadSolicitada")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("IdCompra")
                        .HasColumnType("int");

                    b.Property<int>("IdMaterial")
                        .HasColumnType("int");

                    b.Property<int>("IdRequisicion")
                        .HasColumnType("int");

                    b.Property<string>("TallaSolicitada")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdRequisicionDetalle");

                    b.HasIndex("IdCompra");

                    b.HasIndex("IdMaterial");

                    b.HasIndex("IdRequisicion");

                    b.ToTable("RequisicionesEPPDetalle");
                });

            modelBuilder.Entity("VH.Services.Entities.Rol", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("VH.Services.Entities.RolPermiso", b =>
                {
                    b.Property<int>("IdRolPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRolPermiso"));

                    b.Property<int>("IdModulo")
                        .HasColumnType("int");

                    b.Property<string>("IdRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ModuloIdModulo")
                        .HasColumnType("int");

                    b.Property<bool>("PuedeCrear")
                        .HasColumnType("bit");

                    b.Property<bool>("PuedeEditar")
                        .HasColumnType("bit");

                    b.Property<bool>("PuedeEliminar")
                        .HasColumnType("bit");

                    b.Property<bool>("PuedeVer")
                        .HasColumnType("bit");

                    b.Property<string>("RolId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdRolPermiso");

                    b.HasIndex("IdModulo");

                    b.HasIndex("ModuloIdModulo");

                    b.HasIndex("RolId");

                    b.HasIndex("IdRol", "IdModulo")
                        .IsUnique();

                    b.ToTable("RolPermisos");
                });

            modelBuilder.Entity("VH.Services.Entities.UnidadMedida", b =>
                {
                    b.Property<int>("IdUnidadMedida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnidadMedida"));

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdUnidadMedida");

                    b.ToTable("UnidadesMedida");
                });

            modelBuilder.Entity("VH.Services.Entities.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("VH.Services.Entities.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("VH.Services.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("VH.Services.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("VH.Services.Entities.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VH.Services.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("VH.Services.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VH.Services.Entities.AlertaConsumo", b =>
                {
                    b.HasOne("VH.Services.Entities.Empleado", "Empleado")
                        .WithMany("Alertas")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VH.Services.Entities.EntregaEPP", "Entrega")
                        .WithMany()
                        .HasForeignKey("IdEntrega")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VH.Services.Entities.MaterialEPP", "Material")
                        .WithMany("Alertas")
                        .HasForeignKey("IdMaterial")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VH.Services.Entities.Proyecto", "Proyecto")
                        .WithMany("Alertas")
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VH.Services.Entities.RequisicionEPP", "Requisicion")
                        .WithMany()
                        .HasForeignKey("IdRequisicion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VH.Services.Entities.Usuario", "UsuarioReviso")
                        .WithMany()
                        .HasForeignKey("IdUsuarioReviso")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empleado");

                    b.Navigation("Entrega");

                    b.Navigation("Material");

                    b.Navigation("Proyecto");

                    b.Navigation("Requisicion");

                    b.Navigation("UsuarioReviso");
                });

            modelBuilder.Entity("VH.Services.Entities.Almacen", b =>
                {
                    b.HasOne("VH.Services.Entities.Proyecto", "Proyecto")
                        .WithMany("Almacenes")
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("VH.Services.Entities.CompraEPP", b =>
                {
                    b.HasOne("VH.Services.Entities.Almacen", "Almacen")
                        .WithMany("Compras")
                        .HasForeignKey("IdAlmacen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VH.Services.Entities.MaterialEPP", "Material")
                        .WithMany("Compras")
                        .HasForeignKey("IdMaterial")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VH.Services.Entities.Proveedor", "Proveedor")
                        .WithMany("Compras")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Almacen");

                    b.Navigation("Material");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("VH.Services.Entities.ConceptoPartida", b =>
                {
                    b.HasOne("VH.Services.Entities.Proyecto", "Proyecto")
                        .WithMany("ConceptosPartidas")
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VH.Services.Entities.UnidadMedida", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("IdUnidadMedida")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("VH.Services.Entities.ConfiguracionMaterialEPP", b =>
                {
                    b.HasOne("VH.Services.Entities.MaterialEPP", "Material")
                        .WithOne("Configuracion")
                        .HasForeignKey("VH.Services.Entities.ConfiguracionMaterialEPP", "IdMaterial")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("VH.Services.Entities.Empleado", b =>
                {
                    b.HasOne("VH.Services.Entities.Proyecto", "Proyecto")
                        .WithMany("Empleados")
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VH.Services.Entities.Puesto", "PuestoCatalogo")
                        .WithMany("Empleados")
                        .HasForeignKey("IdPuesto")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Proyecto");

                    b.Navigation("PuestoCatalogo");
                });

            modelBuilder.Entity("VH.Services.Entities.EntregaEPP", b =>
                {
                    b.HasOne("VH.Services.Entities.CompraEPP", "Compra")
                        .WithMany()
                        .HasForeignKey("IdCompra")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VH.Services.Entities.Empleado", "Empleado")
                        .WithMany("EntregasEPP")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("VH.Services.Entities.EstadisticaEmpleadoMensual", b =>
                {
                    b.HasOne("VH.Services.Entities.Empleado", "Empleado")
                        .WithMany("Estadisticas")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VH.Services.Entities.Proyecto", "Proyecto")
                        .WithMany()
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("VH.Services.Entities.EstadisticaProyectoMensual", b =>
                {
                    b.HasOne("VH.Services.Entities.Proyecto", "Proyecto")
                        .WithMany("Estadisticas")
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("VH.Services.Entities.Inventario", b =>
                {
                    b.HasOne("VH.Services.Entities.Almacen", "Almacen")
                        .WithMany("Inventarios")
                        .HasForeignKey("IdAlmacen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VH.Services.Entities.MaterialEPP", "Material")
                        .WithMany("Inventarios")
                        .HasForeignKey("IdMaterial")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Almacen");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("VH.Services.Entities.LogActividad", b =>
                {
                    b.HasOne("VH.Services.Entities.Usuario", "Usuario")
                        .WithMany("LogsActividad")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VH.Services.Entities.MaterialEPP", b =>
                {
                    b.HasOne("VH.Services.Entities.UnidadMedida", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("IdUnidadMedida")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("VH.Services.Entities.Modulo", b =>
                {
                    b.HasOne("VH.Services.Entities.Modulo", "ModuloPadre")
                        .WithMany("SubModulos")
                        .HasForeignKey("IdModuloPadre")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ModuloPadre");
                });

            modelBuilder.Entity("VH.Services.Entities.RequisicionEPP", b =>
                {
                    b.HasOne("VH.Services.Entities.Almacen", "Almacen")
                        .WithMany()
                        .HasForeignKey("IdAlmacen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VH.Services.Entities.Empleado", "EmpleadoRecibe")
                        .WithMany()
                        .HasForeignKey("IdEmpleadoRecibe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VH.Services.Entities.Usuario", "UsuarioAprueba")
                        .WithMany()
                        .HasForeignKey("IdUsuarioAprueba")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VH.Services.Entities.Usuario", "UsuarioEntrega")
                        .WithMany()
                        .HasForeignKey("IdUsuarioEntrega")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VH.Services.Entities.Usuario", "UsuarioSolicita")
                        .WithMany()
                        .HasForeignKey("IdUsuarioSolicita")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Almacen");

                    b.Navigation("EmpleadoRecibe");

                    b.Navigation("UsuarioAprueba");

                    b.Navigation("UsuarioEntrega");

                    b.Navigation("UsuarioSolicita");
                });

            modelBuilder.Entity("VH.Services.Entities.RequisicionEPPDetalle", b =>
                {
                    b.HasOne("VH.Services.Entities.CompraEPP", "Compra")
                        .WithMany()
                        .HasForeignKey("IdCompra")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VH.Services.Entities.MaterialEPP", "Material")
                        .WithMany()
                        .HasForeignKey("IdMaterial")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VH.Services.Entities.RequisicionEPP", "Requisicion")
                        .WithMany("Detalles")
                        .HasForeignKey("IdRequisicion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Material");

                    b.Navigation("Requisicion");
                });

            modelBuilder.Entity("VH.Services.Entities.RolPermiso", b =>
                {
                    b.HasOne("VH.Services.Entities.Modulo", "Modulo")
                        .WithMany()
                        .HasForeignKey("IdModulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VH.Services.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VH.Services.Entities.Modulo", null)
                        .WithMany("RolPermisos")
                        .HasForeignKey("ModuloIdModulo");

                    b.HasOne("VH.Services.Entities.Rol", null)
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolId");

                    b.Navigation("Modulo");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("VH.Services.Entities.Almacen", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("VH.Services.Entities.Empleado", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("EntregasEPP");

                    b.Navigation("Estadisticas");
                });

            modelBuilder.Entity("VH.Services.Entities.MaterialEPP", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Compras");

                    b.Navigation("Configuracion");

                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("VH.Services.Entities.Modulo", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("SubModulos");
                });

            modelBuilder.Entity("VH.Services.Entities.Proveedor", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("VH.Services.Entities.Proyecto", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Almacenes");

                    b.Navigation("ConceptosPartidas");

                    b.Navigation("Empleados");

                    b.Navigation("Estadisticas");
                });

            modelBuilder.Entity("VH.Services.Entities.Puesto", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("VH.Services.Entities.RequisicionEPP", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("VH.Services.Entities.Rol", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("VH.Services.Entities.Usuario", b =>
                {
                    b.Navigation("LogsActividad");
                });
#pragma warning restore 612, 618
        }
    }
}
